version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - API_URL=http://api:3001
    depends_on:
      - api
    restart: always

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=bowling_scores
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - PORT=3001
      - HOST=0.0.0.0
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:14
    container_name: bowling_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bowling_scores
    volumes:
      - bowling_postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  bowling_postgres_data:
