version: '3'
services:
  app:
    image: bowling-score-tracker  # Use the specified image
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
